version: "3.7"

services:
  threeifydev:
    image: theiaide/theia
    env_file:
      - .env
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - .:/home/project:cached
    container_name: threeifydev
