name: commitlint

on:
  pull_request:
    branches: "**"
  push:
    branches: "**"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.0"
      - name: install commitlint
        run: npm i @commitlint/{cli,config-conventional}
      - name: vet last commit message
        run: git log -1 --pretty=format:"%s" | npx commitlint
