name: lint

on:
  pull_request:
    branches: "**"
  push:
    branches: "**"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.0"
      - run: npm i
      - run: npm run lint
